service: produce-in-lambda
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  helloREST:
    handler: handlerREST.hello
    events:
      - httpApi:
          path: /helloREST
          method: get
  helloKafkaJS:
    handler: handlerKafkaJS.hello
    events:
      - httpApi:
          path: /helloKafkaJS
          method: get
