#:schema node_modules/wrangler/config-schema.json
name = "cf-redis-wh"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
UPSTASH_REDIS_REST_URL = "YOUR_TOKEN"
UPSTASH_REDIS_REST_TOKEN = "YOUR_TOKEN"

[[durable_objects.bindings]]
name = "CHAT"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]