require 'bundler/setup'
require 'resque'
require 'resque/scheduler/tasks'
require './processes'
require './constants'

Resque.redis = connection_url()



Resque.logger.level = Logger::FATAL
# Resque.redis.namespace = "resque:upstash"